### ISSUE TITLE
Block Visualization

### ISSUE THREAD

**Issue by varadhbhatnagar** [varadhbhatnagar/Blockchain-Beginning#7]
I have created subheadings inside the block. Lets try to fill them one by one is simple words.

**Comment by varadhbhatnagar** [comment]
https://bitcoin.stackexchange.com/questions/70274/why-do-some-blocks-not-have-miners-name-identity/70276#70276 @Tusharchoudhary Sir can you understand? because I could not. [Solved]

**Comment by Tusharchoudhary** [comment]
@varadhbhatnagar is this still unsolved ?

**Comment by varadhbhatnagar** [comment]
@Tusharchoudhary Please comment on format of the transaction i.e. One Input - One Output and so on... I have documented a snap of the transaction structure. Also, strike through text in Bitcoin Transactions is not clear to me.

**Comment by Tusharchoudhary** [comment]
> A transaction is a _transfer of Bitcoin value_ that is __broadcast__ to the network and collected into blocks. A transaction typically references previous transaction outputs as new transaction inputs and dedicates all input Bitcoin values to new outputs. Transactions are __not encrypted__, so it is possible to browse and view every transaction ever collected into a block. Once transactions are buried under enough confirmations they can be considered irreversible.

> Standard transaction outputs nominate addresses, and the redemption of any future inputs requires a relevant signature.

> All transactions are visible in the block chain.

[transaction wiki](https://en.bitcoin.it/wiki/Transaction)

> A Bitcoin wallet is a collection of private keys but may also refer to client software used to manage those keys and to make transactions on the Bitcoin network. 

 ~~Each user's Bitcoins are stored in a program called a digital wallet~~

**Comment by Tusharchoudhary** [comment]
@varadhbhatnagar you want to discuss the example in the wiki ?

**Comment by varadhbhatnagar** [comment]
@Tusharchoudhary I understood it with the help of this video here : https://www.youtube.com/watch?v=Lx9zgZCMqXE.

**Comment by Tusharchoudhary** [comment]
document in doc
