### ISSUE TITLE
Does anyone have an idea why root hash and block hash are different?

### ISSUE THREAD

**Issue by varadhbhatnagar** [varadhbhatnagar/Blockchain-Beginning#8]
https://bitcoin.stackexchange.com/questions/70336/what-is-the-difference-between-root-hash-and-block-hash [Solved]

**Comment by varadhbhatnagar** [comment]
Also, @Tusharchoudhary 
1. What happens when all the coins get mined? Bitcoin is rendered just a trading currency?[Solved]
2. What is stopping two of the biggest mining pools from colluding and disrupting the network with their superior processing power? [Solved]
3. What happens if a block doesn't get solved and becomes full of transactions?[Solved]

**Comment by ravirocx** [comment]
Regarding point 1 
if all coins get mined, then miners only source of incentives will be transaction fees. This will have a negeative impact on bitcoins, like no. of miners will be reduced, type of centralized bitcoin network. Just transaction fees will be insufficient for miners, just hope that mining technology develops to cheap and efficient mining devices.

**Comment by varadhbhatnagar** [comment]
What kind of incentive is there other than bitcoin? What is transaction fee as an incentive?

From Satoshi's paper, what does this mean ?
"The incentive can also be funded with transaction fees.  If the output value of a transaction is less than its input value, the difference is a transaction fee that is added to the incentive value of the block containing the transaction."

**Comment by ravirocx** [comment]
The amount of processing power to generate an entire new block chain versus the honest chains is frankly not worth the effort versus legitimately processing the block chain honestly.
read para 11 for more information (i am unable to understand that para, but people in forums and comments of articles say that probability of controlling blockchain network is negligible.
and, there is no such incentives other than bitcoin directing towards miner, but if all coins are mined miners would be forced to levy transaction fees to be afloat.

**Comment by Tusharchoudhary** [comment]
3. Happens all the time, the particular miner loses the race, and someone else mines the block. The difficulty is chosen as such that with the available hashpower the block gets mined within a limit of time

**Comment by Tusharchoudhary** [comment]
2. Bitcoin or any currency only has value until its not corrupt, the moment people loose trust the value will be nullified.
para just say reward+fee is easier than cheating.

**Comment by Tusharchoudhary** [comment]
@varadhbhatnagar read about transaction fees, you understand even better when we'll host it on our private net and do transactions.

**Comment by varadhbhatnagar** [comment]
@Tusharchoudhary  in point 3 you said that the miner loses the race and block gets mined by someone else but the block is the same for everyone and it should have been full of transactions too.

**Comment by Tusharchoudhary** [comment]
block may not be same for everyone.
to gain as much as possible the miners would want to include as many transactions in the block as the size permits, reach 'full' capacity. Different miners may include different transactions or different order of transactions.
And then they try to mine the block, ie try to find a nounce which concatenated with the block produces a hash less than target

**Comment by varadhbhatnagar** [comment]
@Tusharchoudhary okay and these are transactions are basically trades happening in the real world?
@ravirocx Please elaborate on txn fee.

**Comment by Tusharchoudhary** [comment]
don't confuse trading on exchange with bitcoin transaction. Yes, these are real world transactions.

txn fees are like bounties, among so many transactions I want my transaction to be processed first so I pay a higher bounty.

**Comment by varadhbhatnagar** [comment]
@Tusharchoudhary Okay, so in the future when bitcoin incentive will be zero, the txn fee will be the main motive to mine blocks. Also, the txn fee is paid by the sender?

**Comment by Tusharchoudhary** [comment]
yes. yes.
