### ISSUE TITLE
define scripts

### ISSUE THREAD

**Issue by Tusharchoudhary** [varadhbhatnagar/Blockchain-Beginning#9]
Block Reward:
Every block also contains a record of which Bitcoin addresses or scripts are entitled to receive the reward.

what do you mean by scripts?

**Comment by varadhbhatnagar** [comment]
@ravirocx  You documented this?

**Comment by ravirocx** [comment]
i have read about the script mentioned above, but i was hardly able to understand that.
https://en.bitcoin.it/wiki/Script

**Comment by Tusharchoudhary** [comment]
read wiki for transactions, you'll know more when we implement private testnet
